# Generated by Django 6.0.6 on 2026-06-29 19:23

import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'دانش\u200cآموز'), ('teacher', 'معلم'), ('admin', 'مدیر'), ('parent', 'والدین')], default='student', max_length=10, verbose_name='نوع کاربر')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید ۱۰ رقم باشد')], verbose_name='کد ملی')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره تلفن باید با ۰۹ شروع شود و ۱۱ رقم باشد')], verbose_name='تلفن همراه')),
                ('grade', models.CharField(blank=True, choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم'), ('graduate', 'فارغ\u200cالتحصیل')], max_length=10, null=True, verbose_name='پایه تحصیلی')),
                ('field', models.CharField(blank=True, choices=[('riazi', 'ریاضی'), ('tajrobi', 'تجربی'), ('ensani', 'انسانی'), ('other', 'سایر')], max_length=10, null=True, verbose_name='رشته تحصیلی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('profile_image', models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/%Y/%m/%d/', verbose_name='تصویر پروفایل')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره من')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدرسه')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='تلفن تأیید شده')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی ثبت\u200cنام')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی آخرین ورود')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
                'permissions': [('can_manage_users', 'می\u200cتواند کاربران را مدیریت کند'), ('can_view_statistics', 'می\u200cتواند آمار را مشاهده کند'), ('can_export_data', 'می\u200cتواند داده\u200cها را خروجی بگیرد')],
            },
        ),
    ]
