# Generated by Django 6.0.6 on 2026-06-29 19:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مرکز')),
                ('center_type', models.CharField(choices=[('school', 'مدرسه'), ('exam_center', 'مرکز برگزاری آزمون'), ('institute', 'آموزشگاه'), ('other', 'سایر')], default='school', max_length=20, verbose_name='نوع مرکز')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='موقعیت مکانی')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانش\u200cآموز')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'مرکز آموزشی',
                'verbose_name_plural': 'مراکز آموزشی',
            },
        ),
    ]
